### ISSUE TITLE
Create a new node type for H2O that can run celery and application code in dev, stage, and prod

### ISSUE THREAD

**Issue by lizadaly** [harvard-lil/h2o#1797]
Should also have the playwright binary/chromium installation for the PDF process.

**Comment by bensteinberg** [comment]
In another context (thread-keeper), I'm installing playwright and chrome like this:
```
nodejs-source:
  cmd.run:
    - name: curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    - shell: /bin/bash
    - creates: /etc/apt/sources.list.d/nodesource.list

nodejs:
  pkg.installed:
    - requires:
      - cmd: nodejs-source

install-chrome:
  cmd.run:
    - name: mkdir -p /tmp/pwt && cd /tmp/pwt && npm install @playwright/test && npx playwright install chrome --force
    - shell: /bin/bash
```
Does that seem plausible?
