### ISSUE TITLE
Reading mode has no maximum line length

### ISSUE THREAD

**Issue by ProbablyFaiz** [harvard-lil/h2o#2026]
Hello! I've been using OpenCasebook for a little while now, and like it a lot for reading casebooks. Reading Mode in particular is great, but for one problem: there's no maximum line length, so on large displays it can become quite [difficult to read](https://www.mediawiki.org/wiki/Reading/Web/Desktop_Improvements/Features/Limiting_content_width). Here's an example (on a 27" 4K monitor):
<img width="2546" alt="image" src="https://github.com/harvard-lil/h2o/assets/34611522/60fe7b51-04da-4e5f-9f72-24c3538a2ec8">

Not that this is the best way to accomplish this, but just as an illustration, I'm able to make things much more readable for myself with the following style changes:
```css
main {
    max-width: 1440px;
    margin: 0 auto;
}
main > div > article {
    max-width: 960px;
    margin-right: 10%;
}
```
Which produces the following layout:
<img width="2548" alt="image" src="https://github.com/harvard-lil/h2o/assets/34611522/94b685df-da94-4205-94a2-7743e885b556">

Happy to take a stab at filing a PR for this, just let me know. Thanks!
